---
development:
  cloud_name: dhic9kypo
  api_key: '231513992291381'
  api_secret: zN6118iBAFREoTsiAoyXrgNJTDE
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dhic9kypo
  api_key: '231513992291381'
  api_secret: zN6118iBAFREoTsiAoyXrgNJTDE
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dhic9kypo
  api_key: '231513992291381'
  api_secret: zN6118iBAFREoTsiAoyXrgNJTDE
  enhance_image_tag: true
  static_image_support: false
