# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e01f3d0be5fa249664832e53d1b5d3c6e4bfd31f63c4de69ccfc1a7b27b6b659834f65c22772f5db8cd058842401050f0fdc230426c7a16d2a69b7ef51926f1e

test:
  secret_key_base: 5306c04c0847f655802114d17ec6e16a7320ceb5695b996fba955e4981d390af23edd0f2f5304fc9b516711e3115269496ce251264f73c849b163b5e52891cf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
